/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package thorium.ui;

import org.gradle.api.Project;
import org.gradle.testfixtures.ProjectBuilder;
import org.junit.Test;

import static org.junit.Assert.*;

/**
 * A simple unit test for the 'thorium.ui.greeting' plugin.
 */
public class ThoriumUiPluginTest {
    @Test public void pluginRegistersATask() {
        // Create a test project and apply the plugin
        Project project = ProjectBuilder.builder().build();
        project.getPlugins().apply("thorium.ui.greeting");

        // Verify the result
        assertNotNull(project.getTasks().findByName("greeting"));
    }
}
